set number
set fileencodings=utf-8,sjis,euc-jp,default

set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4

set ignorecase
set smartcase
set incsearch

inoremap <silent> jj <ESC>
